#!/bin/bash -xv

# Get the DB endpoint
tfstate=$(aws s3 cp s3://$S3BUCKENT/env:/$ENVIRONMENT/terraform.tfstate -)

dbserver=$(echo "$tfstate" | jq -r '.outputs."db-hostname".value')
dbuser=$(echo "$tfstate" | jq -r '.outputs."db-user".value')
dbname=$(echo "$tfstate" | jq -r '.outputs."db-name".value')

echo "Using dbserver: $dbserver"

if ! mysql -h $dbserver -u $dbuser -p$DBPASS $dbname <sql/02.sql
then
  echo "Failed to create schema for Petclinic" 1>&2
  exit 1
fi
if ! mysql -h $dbserver -u $dbuser -p$DBPASS $dbname <sql/03.sql
then
  echo "Failed to load data for Petclinic" 1>&2
  exit 2
fi
