version: "3.7"
services:
  mysql:
    image: mariadb:10.8.3
    container_name: mysql
    volumes:
      - type: bind
        source: ./sql
        target: /docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    image: petclinic
    container_name: petclinic
    ports:
      - 1080:8080
    environment:
      - DBSERVERNAME=mysql
      - DBUSERNAME=root
      - DBPASSWORD=petclinic
