#!/bin/bash -xv

currentdir=$PWD

if [[ ! -e ../terraform ]]
then
  cd ..
  wget https://releases.hashicorp.com/terraform/0.14.0/terraform_0.14.0_linux_amd64.zip | unzip -
  chmod +x terraform
fi

cd $currentdir

if [[ -z $BUCKETNAME ]] || [[ -z $ENVIRONMENT ]] || [[ -z $REGION ]]
then
  echo "The following environment variables need to be set;"
  echo "* BUCKETNAME"
  echo "* ENVIRONMENT"
  echo "* REGION"
  exit 1
fi

cat >state.tf <<_END_
data "terraform_remote_state" "petclinic" {
  backend = "s3"
  config = {
    bucket = "$BUCKETNAME"
    key    = "$ENVIRONMENT/terraform.tfstate"
    region = "$REGION"
  }
}
_END_

cat >backend.tf <<_END_
terraform {
  backend "s3" {
    bucket = "$BUCKETNAME"
    key    = "$ENVIRONMENT/pc/terraform.tfstate"
    region = "$REGION"
  }
}
_END_

if ../terraform apply -auto-approve
then
  echo "SUCCESS"
else
  echo "FAILURE"
  exit 1
fi
