#!/bin/bash -xv

currentdir=$PWD

if [[ ! -e ../bin/terraform ]]
then
  if [[ ! -d ../bin ]]
  then
    mkdir ../bin
  fi
  cd ../bin
  wget https://releases.hashicorp.com/terraform/0.14.0/terraform_0.14.0_linux_amd64.zip
  unzip terraform_0.14.0_linux_amd64.zip
  chmod +x terraform
fi

cd $currentdir

if [[ -z $BUCKETNAME ]] || [[ -z $ENVIRONMENT ]] || [[ -z $REGION ]]
then
  echo "The following environment variables need to be set;"
  echo "* BUCKETNAME"
  echo "* ENVIRONMENT"
  echo "* REGION"
  exit 1
fi

cat >state.tf <<_END_
data "terraform_remote_state" "petclinic" {
  backend = "s3"
  config = {
    bucket = "$BUCKETNAME"
    key    = "$ENVIRONMENT/terraform.tfstate"
    region = "$REGION"
  }
}
_END_

cat >backend.tf <<_END_
terraform {
  backend "s3" {
    bucket = "$BUCKETNAME"
    key    = "$ENVIRONMENT/pc/terraform.tfstate"
    region = "$REGION"
  }
}
_END_

cat >provider.tf <<_END_
provider "aws" {
  region = "$REGION"
}
_END_

if ! ../bin/terraform init
then
  echo "TF init failed"
  rm -rf .terraform
  exit 1
fi

# Set workspace
if ! ../bin/terraform workspace new $ENVIRONMENT
then
  echo "Failed to create environment"
  if ! ../bin/terraform workspace select $ENVIRONMENT
  then
    echo "Failed to select environment"
    rm -rf .terraform
    exit 2
  fi
fi

if ../bin/terraform destroy -auto-approve
then
  echo "SUCCESS"
else
  echo "FAILURE"
  exit 3
fi
